/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Fri Jun 27 13:14:28 2014
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


